## Parameters to configure the runtime at compile time

#### use VERBOSE=X to enable debug messages up to level X, VERBOSE=0 to disable them
#### Typical values are 0, 1, 10, 100, 1000
VERBOSE=1

#### Set to 1 to enable support for dependencies between tasks
WITH_DEPENDENCIES=0

#### Initial size of the task queue(s)
QUEUE_SIZE=16

#### Number of threads in the worker pool
THREAD_COUNT=4
