#include <stdlib.h>
#include <assert.h>

#include "tasks.h"

/* !!! None of these functions need to be modified until stage B2 */

/* Appends 'e' to the list of params */
static void param_list_append(task_param_t **list, task_param_t *e)
{   
    if (*list == NULL){
        *list = e;
        return;
    }

    task_param_t *iter = *list;
    
    while(iter->next != NULL){
        iter = iter->next;
    }

    iter->next = e;
}

/* Retrieves the first element from the list of params */
static task_param_t* param_list_remove_first(task_param_t **list)
{
    task_param_t *elem = *list;;

    assert(elem != NULL);   
     
    *list = elem->next;
    
    return elem;
}

/* Allocates a region of size 's' and appends it as param to the list
 * of params */
static task_param_t* attach_param(task_param_t **list, size_t s)
{
    task_param_t* param = malloc(sizeof(task_param_t));

    param->next = NULL;
    param->elem = malloc(s);

    param_list_append(list, param);

    return param;
}

#ifdef WITH_DEPENDENCIES
/* Creates a new parameter (without allocating a memory region) and
 * appends it to the list of params */
static task_param_t* attach_param_with_elem(task_param_t **list, void* elem)
{
    task_param_t* param = malloc(sizeof(task_param_t));

    param->next = NULL;
    param->elem = elem;

    param_list_append(list, param);

    return param;
}
#endif

/* Retrieves one parameter from a list */
static task_param_t* retrieve_param(task_param_t **list)
{
    return param_list_remove_first(list);
}

/* Allocates 's' bytes and attaches a new input parameter to task 't'*/
void* attach_input(task_t *t, size_t s)
{
    task_param_t* param = attach_param(&t->tstate.input_list, s);
    
    return param->elem;
}

/* Allocates 's' bytes and attaches a new output parameter to task 't'*/
void* attach_output(task_t *t, size_t s)
{
    task_param_t* param = attach_param(&t->tstate.output_list, s);

#ifdef WITH_DEPENDENCIES
    if(active_task != NULL){
        /* the active task is interested in the outputs */
        attach_param_with_elem(&active_task->tstate.output_from_dependencies_list, param->elem);
        return param->elem;
    }
    else{
        return param->elem;
    }
#endif
    
    return param->elem;
}

/* Retrieves the next input parameter of task 't'*/
/* parameters are retrieved in the order they have been attached */
void* retrieve_input(task_t *t)
{
    task_param_t *param = retrieve_param(&t->tstate.input_list);

    return param->elem;
}

/* Retrieves the next output parameter of task 't'*/
/* parameters are retrieved in the order they have been attached */
void* retrieve_output(task_t *t)
{
    task_param_t *param = retrieve_param(&t->tstate.output_list);
    
    return param->elem;
}

#ifdef WITH_DEPENDENCIES
/* Retrieves an output paramter generated by a child task of task 't' */
void* retrieve_output_from_dependencies(task_t *t)
{
    task_param_t *param = retrieve_param(&t->tstate.output_from_dependencies_list);
    
    return param->elem;
}
#else
void* retrieve_output_from_dependencies(task_t *t)
{
    return NULL;
}
#endif
