package team.lmao.ast;

import team.lmao.ast.types.*;
import team.lmao.ast.expressions.*;
import team.lmao.utils.Pair;

import java_cup.runtime.*;
import java.io.Reader;
import java.util.*;


class ASTParser;

parser code {:
    private ASTLexer lexer;

    public ASTParser(Reader reader) {
        super(new ComplexSymbolFactory());
	    this.lexer = new ASTLexer(reader, (ComplexSymbolFactory) this.symbolFactory);
    }
 :}

init with {:  :};
scan with {: return lexer.next_token(); :};

terminal boolean BOOL;
terminal int INT;
terminal float FLOAT;
terminal Id IDENT;
terminal NOT, MINUS, PLUS, MINUS_DOT, PLUS_DOT, AST_DOT, SLASH_DOT, EQUAL, LESS_GREATER, LESS_EQUAL, GREATER_EQUAL, LESS, GREATER, IF, THEN, ELSE, LET, IN, REC, COMMA, ARRAY_CREATE, DOT, LESS_MINUS, SEMICOLON, LPAREN, RPAREN;
terminal prec_let, prec_if, prec_unary_minus, prec_app;

non terminal List<ASTExpression> elems;
non terminal List<ASTExpression> actual_args;
non terminal List<Id> formal_args;
non terminal Pair<List<Id>, List<Type>>  pat;
non terminal ASTFunctionDefine fundef;
non terminal ASTExpression simple_exp;
non terminal ASTExpression exp;

precedence right prec_let;
precedence right SEMICOLON;
precedence right prec_if;
precedence right LESS_MINUS;
precedence left COMMA;
precedence left EQUAL, LESS_GREATER, LESS, GREATER, LESS_EQUAL, GREATER_EQUAL;
precedence left PLUS, MINUS, PLUS_DOT, MINUS_DOT;
precedence left AST_DOT, SLASH_DOT;
precedence right prec_unary_minus;
precedence left prec_app;
precedence left DOT;
precedence nonassoc INT, FLOAT, IDENT, LPAREN;

start with exp;

simple_exp ::= LPAREN exp:e RPAREN                    {: RESULT = e; :}
             | LPAREN RPAREN                          {: RESULT = new ASTUnit(); :}
             | BOOL:b                                 {: RESULT = new ASTBoolean(b); :}
             | INT:i                                  {: RESULT = new ASTInteger(i); :}
             | FLOAT:f                                {: RESULT = new ASTFloat(f); :}
             | IDENT:id                               {: RESULT = new ASTVariable(id); :}
             | simple_exp:e1 DOT LPAREN exp:e2 RPAREN {: RESULT = new ASTGet(e1, e2); :}
;

exp ::= simple_exp:e                                             {: RESULT = e; :}
      | NOT exp:e                                                {: RESULT = new ASTBooleanNot(e); :} %prec prec_app
      | MINUS exp:e                                              {: if (e instanceof ASTFloat) RESULT = new ASTFloat(-((ASTFloat) e).f); else RESULT = new ASTIntegerNegative(e); :} %prec prec_unary_minus
      | exp:e1 PLUS exp:e2                                       {: RESULT = new ASTIntegerAdd(e1, e2); :}
      | exp:e1 MINUS exp:e2                                      {: RESULT = new ASTIntegerSubtract(e1, e2); :}
      | exp:e1 EQUAL exp:e2                                      {: RESULT = new ASTIntegerEqual(e1, e2); :}
      | exp:e1 LESS_GREATER exp:e2                               {: RESULT = new ASTBooleanNot(new ASTIntegerEqual(e1, e2)); :}
      | exp:e1 LESS exp:e2                                       {: RESULT = new ASTBooleanNot(new ASTIntegerLessOrEqual(e2, e1)); :}
      | exp:e1 GREATER exp:e2                                    {: RESULT = new ASTBooleanNot(new ASTIntegerLessOrEqual(e1, e2)); :}
      | exp:e1 LESS_EQUAL exp:e2                                 {: RESULT = new ASTIntegerLessOrEqual(e1, e2); :}
      | exp:e1 GREATER_EQUAL exp:e2                              {: RESULT = new ASTIntegerLessOrEqual(e2, e1); :}
      | IF exp:e1 THEN exp:e2 ELSE exp:e3                        {: RESULT = new ASTIf(e1, e2, e3); :} %prec prec_if
      | MINUS_DOT exp:e                                          {: RESULT = new ASTFloatNegative(e); :} %prec prec_unary_minus
      | exp:e1 PLUS_DOT exp:e2                                   {: RESULT = new ASTFloatAdd(e1, e2); :}
      | exp:e1 MINUS_DOT exp:e2                                  {: RESULT = new ASTFloatSubtract(e1, e2); :}
      | exp:e1 AST_DOT exp:e2                                    {: RESULT = new ASTFloatMultiply(e1, e2); :}
      | exp:e1 SLASH_DOT exp:e2                                  {: RESULT = new ASTFloatDivide(e1, e2); :}
      | LET IDENT:id EQUAL exp:e1 IN exp:e2                      {: RESULT = new ASTLet(id, Type.gen(), e1, e2); :} %prec prec_let
      | LET REC fundef:fd IN exp:e                               {: RESULT = new ASTLetRec(fd,  e); :} %prec prec_let
      | exp:e actual_args:es                                     {: RESULT = new ASTApp(e, es); :} %prec prec_app
      | elems:es                                                 {: RESULT = new ASTTuple(es); :}
      | LET LPAREN pat:p RPAREN EQUAL exp:e1 IN exp:e2           {: RESULT = new ASTLetTuple(p.left, p.right, e1, e2); :}
      | simple_exp:e1 DOT LPAREN exp:e2 RPAREN LESS_MINUS exp:e3 {: RESULT = new ASTPut(e1, e2, e3); :}
      | exp:e1 SEMICOLON exp:e2                                  {: RESULT = new ASTLet(Id.gen(), new TypeUnit(), e1, e2); :}
      | ARRAY_CREATE simple_exp:e1 simple_exp:e2                 {: RESULT = new ASTArray(e1, e2); :} %prec prec_app
      | error                                                    {: RESULT = null; :}
;

fundef ::= IDENT:name formal_args:args EQUAL exp:e {: RESULT = new ASTFunctionDefine(name, null, args, e); :}
         | IDENT:name EQUAL exp:e                  {: RESULT = new ASTFunctionDefine(name, null,  new LinkedList(), e); :}
;

formal_args ::= IDENT:id formal_args:args {: args.add(0, id); RESULT = args; :}
              | IDENT:id                  {: RESULT = new LinkedList(Arrays.asList(id)); :}
;

actual_args ::= actual_args:es simple_exp:e {: es.add(e); RESULT = es; :} %prec prec_app
              | simple_exp:e                {: RESULT = new LinkedList(Arrays.asList(e)); :} %prec prec_app
;

elems ::= elems:es COMMA exp:e {: es.add(e); RESULT = es; :}
        | exp:e1 COMMA exp:e2  {: RESULT = new LinkedList(Arrays.asList(e1, e2)); :}
;

pat ::= pat:is COMMA IDENT:i    {: is.left.add(i); RESULT = is; :}
      | IDENT:i1 COMMA IDENT:i2 {: RESULT = new Pair(new LinkedList(Arrays.asList(i1, i2)), new LinkedList(Arrays.asList(Type.gen(), Type.gen()))); :}
;
