#### Definition of the size of the memory pool

## TIP1: It can make sense to test small pool sizes to test corner cases where an allocation would fail

## TIP2: Some programs (such as 'ps') require allocating large memory blocks. Increase the size of the pool to handle such cases (for instance, giving a size of 10485760 (10MB))

MEM_POOL_SIZE=1024

#### Definition of the allocation policy

## possible values are FF, BF, WF and NF

ALLOC_POLICY=FF


#### Definition of the memory alignment constraint

MEM_ALIGNMENT=64
