exercise_4:
	bash 4_shell.sh

prepare_build_dir:
	mkdir -p build

exercise_5: prepare_build_dir
	gcc 5_forks.c -o build/5_forks.run
	./build/5_forks.run 5

exercise_6: prepare_build_dir
	gcc 6_execs.c -o build/6_execs.run
	./build/6_execs.run

exercise_7: prepare_build_dir
	gcc 7_files.c -o build/7_files.run
	./build/7_files.run

exercise_8: prepare_build_dir
	gcc 8_pipes.c -o build/8_pipes.run
	./build/8_pipes.run

exercise_9: prepare_build_dir
	gcc 9_rands.c -o build/9_rands.run
	./build/9_rands.run 6
